### ISSUE TITLE
Exception starting filter [InternalSSOFilter]

### ISSUE THREAD

**Issue by stijni** [Bonitasoft-Community/docker_bonita#22]
During the initial launch of the docker container, I get the following message:

2020-06-30 17:48:05.649 +0000 INFO: org.bonitasoft.engine.EngineInitializer Initialization of Bonita Engine done! ( took 11220ms)
done
2020-06-30 17:48:08.545 +0000 SEVERE: org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/bonita] Exception starting filter [InternalSSOFilter]
java.lang.ClassNotFoundException: org.bonitasoft.console.common.server.sso.filter.InternalSSOFilter
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1358)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1180)
        at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:546)
        at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:527)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:150)
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:106)
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4548)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5193)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:614)
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1823)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

2020-06-30 17:48:08.589 +0000 SEVERE: org.apache.catalina.core.StandardContext One or more Filters failed to start. Full details will be found in the appropriate container log file
2020-06-30 17:48:08.590 +0000 SEVERE: org.apache.catalina.core.StandardContext Context [/bonita] startup failed due to previous errors
2020-06-30 17:48:08.594 +0000 INFO: org.bonitasoft.engine.EngineInitializer Stopping Bonita Engine...
2020-06-30 17:48:08.595 +0000 INFO: org.bonitasoft.engine.EngineInitializer Stopping node...
2020-06-30 17:48:08.624 +0000 INFO: org.quartz.core.QuartzScheduler Scheduler QuartzScheduler_$_NON_CLUSTERED shutting down.
2020-06-30 17:48:08.625 +0000 INFO: org.quartz.core.QuartzScheduler Scheduler QuartzScheduler_$_NON_CLUSTERED paused.
2020-06-30 17:48:08.679 +0000 INFO: org.quartz.core.QuartzScheduler Scheduler QuartzScheduler_$_NON_CLUSTERED shutdown complete.
2020-06-30 17:48:08.697 +0000 INFO: org.bonitasoft.engine.EngineInitializer Bonita Engine stopped!
2020-06-30 17:48:09.272 +0000 SEVERE: org.apache.catalina.loader.WebappClassLoaderBase The web application [bonita] created a ThreadLocal with key of type [org.bonitasoft.engine.transaction.JTATransactionServiceImpl.TransactionServiceContextThreadLocal] (value [org.bonitasoft.engine.transaction.JTATransactionServiceImpl$TransactionServiceContextThreadLocal@69c32446]) and a value of type [org.bonitasoft.engine.transaction.JTATransactionServiceImpl.TransactionServiceContext] (value [org.bonitasoft.engine.transaction.JTATransactionServiceImpl$TransactionServiceContext@28b23de8]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
2020-06-30 17:48:09.277 +0000 INFO: org.apache.catalina.startup.HostConfig Deployment of deployment descriptor [/opt/bonita/BonitaCommunity-7.11.0/server/conf/Catalina/localhost/bonita.xml] has finished in [16,666] ms
2020-06-30 17:48:09.279 +0000 INFO: org.apache.coyote.http11.Http11NioProtocol Starting ProtocolHandler ["http-nio-8080"]
2020-06-30 17:48:09.289 +0000 INFO: org.apache.catalina.startup.Catalina Server startup in 16924 ms

**Comment by baptistemesta** [comment]
Thank you for the report, there was indeed an issue while creating the new image.
The following PR should fix that.
https://github.com/Bonitasoft-Community/docker_bonita/pull/21

**Comment by baptistemesta** [comment]
Hello. 
PR #21 was merged and should fix this issue.
I will push these changes on Docker hub soon.
Do you want to validate the fix before I close this issue?

Thanks again for the report.

**Comment by stijni** [comment]
Working now: Welcome to Bonita Portal.

Thanks for the quick support

**Comment by baptistemesta** [comment]
Perfect, thank you!
